### ISSUE TITLE
Unsafe use of eval

### ISSUE THREAD

**Issue by cristianstaicu** [floatinghotpot/mixin-pro#1]
In mixin.js, the folowing code is unsafe: 

``` js
function mixin_constructor(name, ctor) {
  var str = "function __ctor() { var c = ctor.constructors; for (var i in c) { c[i].apply(this, arguments); } };".replace(/__ctor/g, name);
  eval(str);
  return eval(name);
}
```

The name parameter may be a non-valid identifier. Consider replacing eval, use ad-hoc regex validation or use a more advanced sanitization  package, like: 
https://www.npmjs.com/package/eval-sanitizer

**Comment by floatinghotpot** [comment]
The class name is defined by developer who is implementing the class. Of course he must ensure the name is valid. Depending on external package will make things heavy and complex.

**Comment by cristianstaicu** [comment]
The problem is when mixin code from other sources, e.g. npm modules. You can have a module exposing something like this: 

``` js
function Foo() {}
Object.defineProperty(Foo, "name", {
    enumerable: false,
    configurable: false,
    writable: true,
    value: 'static'
});
Foo.name = "test2()\n{}; console.log('my very evil code here'); x=function(){};//"
```

**Comment by floatinghotpot** [comment]
Yes, you are correct. How about this simple regex validation?

``` javascript
if(/^[$A-Z_][0-9A-Z_$]*$/i.test(name)) { ... }
```

**Comment by cristianstaicu** [comment]
Seems like it does the job in this case! Don't forget to add the lower chars as well though. Good luck! ;)

**Comment by floatinghotpot** [comment]
The above regex is case insensitive with /i. Thanks for reminder.
